import os
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.graphics.shapes import Drawing, Rect, String, Group, Line
from reportlab.graphics.charts.barcharts import VerticalBarChart

# Brand Colors
COLOR_BrandGold = colors.HexColor("#D4AF37")
COLOR_DarkHeader = colors.HexColor("#000000")
COLOR_LightGray = colors.HexColor("#f8f9fa")
COLOR_Success = colors.HexColor("#16a34a")
COLOR_Warning = colors.HexColor("#ea580c")
COLOR_Danger = colors.HexColor("#dc2626")

def footer(canvas, doc):
    canvas.saveState()
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(colors.gray)
    canvas.drawString(inch, 0.75 * inch, "© 2026 ZENIAC.CO | Generated by Advanced Intelligence Engine")
    canvas.drawRightString(A4[0] - inch, 0.75 * inch, f"Page {doc.page}")
    canvas.restoreState()

def header(canvas, doc):
    canvas.saveState()
    canvas.setFont('Helvetica-Bold', 18)
    canvas.drawString(inch, A4[1] - 0.75 * inch, "ZENIAC INTELLIGENCE")
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(colors.gray)
    canvas.drawString(inch, A4[1] - 1.0 * inch, "CONFIDENTIAL STRATEGY DOCUMENT")
    canvas.restoreState()

def get_score_color(score):
    if score >= 80: return COLOR_Success
    if score >= 60: return COLOR_BrandGold
    if score >= 40: return COLOR_Warning
    return COLOR_Danger

def generate_pdf_report(analysis_data, output_path):
    doc = SimpleDocTemplate(output_path, pagesize=A4, rightMargin=inch, leftMargin=inch, topMargin=1.5*inch, bottomMargin=1.5*inch)
    story = []
    styles = getSampleStyleSheet()
    
    # Custom Styles
    style_Title = ParagraphStyle('ZTitle', parent=styles['Title'], fontSize=24, spaceAfter=20, textColor=COLOR_DarkHeader)
    style_Heading1 = ParagraphStyle('ZHeading1', parent=styles['Heading1'], fontSize=18, spaceAfter=12, textColor=COLOR_BrandGold, textTransform='uppercase')
    style_Heading2 = ParagraphStyle('ZHeading2', parent=styles['Heading2'], fontSize=14, spaceAfter=10, textColor=COLOR_DarkHeader)
    style_Normal = ParagraphStyle('ZNormal', parent=styles['Normal'], fontSize=10, leading=14, spaceAfter=8)
    style_Score = ParagraphStyle('ZScore', parent=styles['Normal'], fontSize=60, leading=70, alignment=TA_CENTER, textColor=COLOR_BrandGold)
    style_ScoreLabel = ParagraphStyle('ZScoreLabel', parent=styles['Normal'], fontSize=12, alignment=TA_CENTER, textColor=colors.gray, textTransform='uppercase')

    # Data Extraction
    website_url = analysis_data.get('url', 'Unknown URL')
    overall_score = analysis_data.get('score', 0)
    business_name = analysis_data.get('businessName', 'Business')
    generated_at = datetime.now().strftime("%B %d, %Y")

    # =================================================================================================
    # PAGE 1: COVER
    # =================================================================================================
    story.append(Spacer(1, 2*inch))
    story.append(Paragraph("INTELLIGENCE BRIEF", style_ScoreLabel))
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph(website_url.upper(), style_Title))
    story.append(Spacer(1, 1*inch))
    
    # Score Hero
    score_color = get_score_color(overall_score)
    story.append(Paragraph(str(overall_score), ParagraphStyle('HeroScore', parent=style_Score, textColor=score_color)))
    story.append(Paragraph("OVERALL HEALTH SCORE", style_ScoreLabel))
    story.append(Spacer(1, 2*inch))
    
    # Executive Summary (Brief)
    story.append(Paragraph("EXECUTIVE SUMMARY", style_Heading2))
    summary_text = f"""
    Comprehensive digital audit and competitive analysis of {website_url}. 
    This report details technical gaps, SEO positioning, and strategic opportunities calculated 
    by the Zeniac Intelligence Engine.
    """
    story.append(Paragraph(summary_text, style_Normal))
    story.append(PageBreak())

    # =================================================================================================
    # PAGE 2: EXECUTIVE SUMMARY & OPPORTUNITIES
    # =================================================================================================
    story.append(Paragraph("EXECUTIVE SUMMARY", style_Heading1))
    
    # Revenue Opportunity
    rev_impact = analysis_data.get('revenueImpact', {})
    monthly_leak = rev_impact.get('monthlyRevenueLeak', 0)
    if monthly_leak > 0:
        story.append(Paragraph(f"💰 ESTIMATED REVENUE OPPORTUNITY: ${monthly_leak:,}/month", 
                             ParagraphStyle('Opp', parent=style_Heading2, textColor=COLOR_Success)))
        story.append(Spacer(1, 10))

    # Strengths & Weaknesses Table
    strengths = analysis_data.get('strengths', [])[:3]
    weaknesses = analysis_data.get('weaknesses', [])[:3]
    
    data = [["TOP STRENGTHS", "CRITICAL GAPS"]]
    for i in range(max(len(strengths), len(weaknesses))):
        s = strengths[i] if i < len(strengths) else ""
        w = weaknesses[i] if i < len(weaknesses) else ""
        data.append([f"• {s}", f"• {w}"])
        
    t = Table(data, colWidths=[3.2*inch, 3.2*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, 0), colors.HexColor("#dcfce7")),
        ('BACKGROUND', (1, 0), (1, 0), colors.HexColor("#fee2e2")),
        ('TEXTCOLOR', (0, 0), (0, 0), colors.HexColor("#166534")),
        ('TEXTCOLOR', (1, 0), (1, 0), colors.HexColor("#991b1b")),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
    ]))
    story.append(t)
    story.append(Spacer(1, 20))
    
    # Key Recommendations
    story.append(Paragraph("PRIORITY RECOMMENDATIONS", style_Heading2))
    recs = analysis_data.get('recommendations', [])[:5]
    for i, rec in enumerate(recs, 1):
        story.append(Paragraph(f"{i}. {rec.get('title', '')}", ParagraphStyle('RecTitle', parent=style_Normal, fontName='Helvetica-Bold')))
        story.append(Paragraph(rec.get('description', ''), style_Normal))
        story.append(Spacer(1, 5))
        
    story.append(PageBreak())

    # =================================================================================================
    # PAGE 3: TECHNICAL DEEP DIVE
    # =================================================================================================
    story.append(Paragraph("TECHNICAL DEEP DIVE", style_Heading1))
    
    # Tech Specs Grid
    tech_stack = analysis_data.get('techStack', 'Unknown')
    pages_scanned = len(analysis_data.get('allPagesData', [])) or 1
    perf_metrics = analysis_data.get('performanceMetrics', {})
    perf_score = perf_metrics.get('performanceScore', 'N/A')
    
    spec_data = [
        ["TECH STACK", "PAGES SCANNED", "CORE WEB VITALS"],
        [tech_stack, str(pages_scanned), str(perf_score)]
    ]
    t_specs = Table(spec_data, colWidths=[2*inch, 2*inch, 2*inch])
    t_specs.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTSIZE', (0, 1), (-1, 1), 14),
        ('FONTNAME', (0, 1), (-1, 1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.gray),
        ('BOX', (0, 0), (-1, -1), 1, colors.lightgrey),
    ]))
    story.append(t_specs)
    story.append(Spacer(1, 20))
    
    # Pages Table
    story.append(Paragraph("PAGE ANALYSIS", style_Heading2))
    pages = analysis_data.get('allPagesData', [])[:10]
    p_data = [["URL PATH", "TITLE TAG", "STATUS"]]
    for p in pages:
        url_path = p.get('url', '').replace(website_url, '')[:30] or '/'
        title = p.get('title', 'Missing')[:40]
        status = "Indexed" if p.get('title') else "Issues"
        p_data.append([url_path, title, status])
        
    t_pages = Table(p_data, colWidths=[2.5*inch, 2.5*inch, 1.5*inch])
    t_pages.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.black),
        ('TEXTCOLOR', (0, 0), (-1, 0), COLOR_BrandGold),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t_pages)
    story.append(PageBreak())

    # =================================================================================================
    # PAGE 4: SOCIAL PRESENCE
    # =================================================================================================
    story.append(Paragraph("SOCIAL PRESENCE AUDIT", style_Heading1))
    
    social = analysis_data.get('socialPresenceAnalysis', {})
    agg = social.get('aggregate', {})
    
    # Social Stats
    s_data = [
        ["SOCIAL AUTHORITY", "FOLLOWERS", "REVIEWS", "RATING"],
        [str(agg.get('social_presence_score', 0)), 
         str(agg.get('total_followers', 0)), 
         str(agg.get('total_reviews', 0)), 
         f"{agg.get('average_rating', 0):.1f}/5.0"]
    ]
    t_social = Table(s_data, colWidths=[2*inch, 1.5*inch, 1.5*inch, 1.5*inch])
    t_social.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTSIZE', (0, 1), (-1, 1), 16),
        ('TEXTCOLOR', (0, 1), (0, 1), COLOR_BrandGold), 
        ('BOX', (0, 0), (-1, -1), 1, colors.lightgrey),
    ]))
    story.append(t_social)
    story.append(Spacer(1, 20))
    
    # AI Insight
    ai_brief = social.get('ai_analysis', {}).get('strategic_brief', '')
    if ai_brief:
        story.append(Paragraph("🤖 AI STRATEGIC ANALYSIS", style_Heading2))
        story.append(Paragraph(ai_brief, style_Normal))

    # Build PDF
    doc.build(story, onFirstPage=footer, onLaterPages=lambda c, d: (header(c, d), footer(c, d)))
    return output_path
